### ISSUE TITLE
api-pagination 4.8.0 on rails 4.2.x with kaminari results in "NameError: uninitialized constant Pagy" exception

### ISSUE THREAD

**Issue by ShaneBoyer** [davidcelis/api-pagination#101] opened 2018-06-12 20:21 UTC
We don't use Pagy.  We do explicitly specify kaminari in an initializer:
```
ApiPagination.configure do |config|
  config.paginator = :kaminari
```

We've temporarily reverted to 4.7.1 to work around this problem.

**Comment by davidcelis** [comment] 2018-06-12 21:00
This is a duplicate of #98 (which is closed), so I'm gonna close this too. I'm waiting for another pull request to be merged before pushing a new release since it's very close to merging; the only change in 4.8.0 is Pagy support, so you're fine to stay on 4.7.1 for now. Sorry about the trouble!

**Closed by davidcelis** 2018-06-12 21:00 UTC
